CREATE TABLE [Countries] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
  CONSTRAINT [PK_COUNTRIES] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Cities] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
	CountryId integer NOT NULL,
  CONSTRAINT [PK_CITIES] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Hotels] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
	CityId integer NOT NULL,
	CategoryId integer NOT NULL,
  CONSTRAINT [PK_HOTELS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Tours] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
	About varchar(255),
	Price decimal NOT NULL,
	HotelId integer NOT NULL,
	Duration integer NOT NULL,
  CONSTRAINT [PK_TOURS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Clients] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
	Phone varchar(50) NOT NULL UNIQUE,
	Email varchar(100) NOT NULL UNIQUE,
  CONSTRAINT [PK_CLIENTS] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Categories] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
  CONSTRAINT [PK_CATEGORIES] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Sales] (
	Id integer NOT NULL IDENTITY(1,1),
	Name varchar(100) NOT NULL,
	TourId integer NOT NULL,
	ClientId integer NOT NULL,
	BeginDate date NOT NULL,
  CONSTRAINT [PK_SALES] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [Cities] WITH CHECK ADD CONSTRAINT [Cities_fk0] FOREIGN KEY ([CountryId]) REFERENCES [Countries]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Cities] CHECK CONSTRAINT [Cities_fk0]
GO

ALTER TABLE [Hotels] WITH CHECK ADD CONSTRAINT [Hotels_fk0] FOREIGN KEY ([CityId]) REFERENCES [Cities]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Hotels] CHECK CONSTRAINT [Hotels_fk0]
GO
ALTER TABLE [Hotels] WITH CHECK ADD CONSTRAINT [Hotels_fk1] FOREIGN KEY ([CategoryId]) REFERENCES [Categories]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Hotels] CHECK CONSTRAINT [Hotels_fk1]
GO

ALTER TABLE [Tours] WITH CHECK ADD CONSTRAINT [Tours_fk0] FOREIGN KEY ([HotelId]) REFERENCES [Hotels]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Tours] CHECK CONSTRAINT [Tours_fk0]
GO



ALTER TABLE [Sales] WITH CHECK ADD CONSTRAINT [Sales_fk0] FOREIGN KEY ([TourId]) REFERENCES [Tours]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Sales] CHECK CONSTRAINT [Sales_fk0]
GO
ALTER TABLE [Sales] WITH CHECK ADD CONSTRAINT [Sales_fk1] FOREIGN KEY ([ClientId]) REFERENCES [Clients]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Sales] CHECK CONSTRAINT [Sales_fk1]
GO

